language: java

branches:
  only:
    - main

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2/repository/

script:
  - ./mvnw test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
