on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to generate starcharts
    steps:
      - name: starcharts
        uses: MaoLongLong/hello-action@v1 # Uses an action in the root directory
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
