name: Starcharts

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-readme:
    name: Generate starcharts
    runs-on: ubuntu-latest
    steps:
      - uses: MaoLongLong/actions-starcharts@main
        with:
          svg_path: test/starcharts.svg
          github_token: ${{ secrets.GH_TOKEN }}
          repo: "doocs/advanced-java"
          stars_change: 100
